# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

server: true

# plugins:

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

include:
  - _pages
  - _redirects

# Site settings
title: Fecit8 Art Vamps
long-title: F8AV =Fecit8 Art Vamps=
email: zieonweb@gmail.com
description: "We are F8AV and we just love the art - what we see and feel. Our purpose and activities aim to reach POP (Planet Of Peace)."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zieonweb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Australia/Adelaide
year: 2023
start-year: 2002
sitemap: true

# Social networks
social-username:
  twitter_username: f8avzieon
  github_username:  zieonweb

# Content
image_serve_path: "/images" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  comments: []
  endings: []
  #ignore:
    #envs: [local]
  blanklines: false # boolean - strip blank lines and breaks
  profile: false
  startings: []


# Structure
navigation:
  - title: Projects
    url: /
  - title: Fonts
    url: /fonts
  - title: About
    url: /about
  - title: Contact
    url: /contact

permalink: /:title/

# Configure site collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  fonts:
    output: true
    permalink: /fonts/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "fonts"
    values:
      layout: "font"
